### ISSUE TITLE
2020/12/07 ライたす

### ISSUE THREAD

**Issue by marbou090** [t4t5u0/human-life#19]
科目をタグ付けする
プロジェクトを設定する(講義関連)

## 概要
エッセイ提出

Topic 1: Describe three "system administration" tasks that each FUN student should regularly perform on their notebook computer. (Quiz Unit 10)

Topic 2: There are many everyday situations in Japan where women experience discrimination (either positively or negatively). Describe three of them. (Quiz Unit 11)

Topic 3: What are three useful HTML tags that FUN students can use in Moodle? (Quiz Unit 12)

Topic 4: Describe three "novel sentences" that Japanese children might make in Japanese. (Quiz Unit 13)

## リンク・画像など(省略可)
https://hope.c.fun.ac.jp/course/view.php?id=665&section=11

**Comment by t4t5u0** [comment]
![image](https://user-images.githubusercontent.com/48282855/101160528-8924e400-3672-11eb-9d5c-64eb8468665f.png)

![image](https://user-images.githubusercontent.com/48282855/101160561-98a42d00-3672-11eb-91b8-afad3a5d303d.png)


するとよい

**Comment by marbou090** [comment]
いま理解した
