### ISSUE TITLE
2020/12/08 R演習

### ISSUE THREAD

**Issue by t4t5u0** [t4t5u0/human-life#21]
科目をタグ付けする
プロジェクトを設定する(講義関連)

## 概要

レポート１０（主成分分析）

準備１　（レポート２、３、４、６、７と同じ）
サンプルデータ（sample1.txt）を以下URLからデスクトップにダウンロードする。
http://www.iu.a.u-tokyo.ac.jp/~kadota/R/sample1.txt
>3051 genes×38 samples（G1:27 samples, G2:11 samples）からなる二群の遺伝子発現データ。

準備２　（レポート２、３、４、６、７と同じ）データの準備
・カレントディレクトリをデスクトップに移動：メニュー->ファイル->ディレクトリの変更
・ファイルの読み込み： x <- read.table( "sample1.txt", skip=1, row.names = 1 )
・行列に変換：　xm = as.matrix( x )

準備３　以下のコマンドを確認してください。
・G2群の遺伝子発現を目視：image( xm[,28:38] )
・G2群の3051種類遺伝子発現量について主成分分析を実行： q<-prcomp( xm[,28:38] );
　（11サンプルの遺伝子発現パターンを表す成分（主成分）を寄与度の高い順に分離する）
・G2群の遺伝子発現の主成分を目視：image( q$x )
・各主成分の寄与度（Proportion of Variance）を確認：summary(q)
 （第一主成分から順に、0.7454 0.0500 0.04755, ... と見える。
　第一主成分が74.5%, 第二主成分が5.0%, 第三主成分が4.6%、元の遺伝子パターンを説明するの意）

課題　G1群の遺伝子発現量について主成分分析を行い、主成分をイメージ表示した結果のスナップショット画像を提出せよ。また、タイトルには「第一主成分の寄与度」を文言に含めよ。

**Comment by marbou090** [comment]
これいつも水曜夜までなのに今週は火曜夜までなの罠でしょ
殺してくれ

**Comment by t4t5u0** [comment]
わかり

2020年12月8日(火) 23:16 Marubou <notifications@github.com>:

**Comment by t4t5u0** [comment]
わかり哲也
