### ISSUE TITLE
~2021/12/31 道東旅行

### ISSUE THREAD

**Issue by t4t5u0** [t4t5u0/human-life#39]
member @DaisenKudo @EbichanOO
いってみたいところをコメントしていく

**Comment by t4t5u0** [comment]
[〒088-0835 北海道釧路郡釧路町仙鳳趾村オタクパウシ - Google マップ](https://www.google.com/maps/place/%E3%80%92088-0835+%E5%8C%97%E6%B5%B7%E9%81%93%E9%87%A7%E8%B7%AF%E9%83%A1%E9%87%A7%E8%B7%AF%E7%94%BA%E4%BB%99%E9%B3%B3%E8%B6%BE%E6%9D%91%E3%82%AA%E3%82%BF%E3%82%AF%E3%83%91%E3%82%A6%E3%82%B7/data=!4m2!3m1!1s0x5f721cb8a1853d77:0x3e44f71eaacd330a?sa=X&ved=2ahUKEwjgktLn1cHuAhUKc3AKHQvcAyEQ8gEwAXoECAsQAQ)

**Comment by t4t5u0** [comment]
@tomio2480 から

[森のホール(弟子屈/カフェ) - Retty](https://retty.me/area/PRE01/ARE300/SUB30003/100000910596/)

**Comment by t4t5u0** [comment]
同上
[アエプ （a=e-p） - 津別町その他/パン [食べログ]](https://tabelog.com/hokkaido/A0110/A011001/1008986/)

**Comment by tomio2480** [comment]
https://good-hokkaido.info/seseki-onsen/

**Comment by tomio2480** [comment]
http://www.hokkaido-michinoeki.jp/michinoeki/2884/

**Comment by tomio2480** [comment]
鹿事故
https://www.hkd.mlit.go.jp/ky/kn/dou_iji/splaat0000003n3x.html

**Comment by DaisenKudo** [comment]
唯我独尊
https://goo.gl/maps/fakYMWKRU9676eyY8

**Comment by DaisenKudo** [comment]
# 冬に行きたくたくねぇよ！！！！！！！！！！！！！！！運転俺やぞ！？！？！？！？！？！？！？！？！？！？！？！？！？！？！？！？！？！？！？！？

**Comment by DaisenKudo** [comment]
issueのタイトルを「~2021/12/31 道東旅行」に変更してください(流石に忙しすぎて今年度中は無理です)
