### ISSUE TITLE
朝に聴きたい曲リスト 作成 

### ISSUE THREAD

**Issue by t4t5u0** [t4t5u0/human-life#42]
https://open.spotify.com/user/rezvsvhniitx1fypvambvmui7?si=UYstQLujTM-T_auEC63SHQ

編集用
https://open.spotify.com/playlist/1EqWDRQTQE9PRRWn9XQA3t?si=ThECROnNSTyOZCK5WDeE8A&utm_source=copy-link

**Comment by DaisenKudo** [comment]
[https://open.spotify.com/album/5zF6v26PLFKapOQ9gnlMDf?si=kAJj21CqRtKtAOuT6R_Awg](https://open.spotify.com/album/5zF6v26PLFKapOQ9gnlMDf?si=kAJj21CqRtKtAOuT6R_Awg)
